// <auto-generated />
using MarvBotV3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarvBotV3.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190504111454_added_roll_tbGoldGambles")]
    partial class added_roll_tbGoldGambles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MarvBotV3.Database.Tables.TbCurrency", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AmountOfGambles");

                    b.Property<long>("GoldAmount");

                    b.Property<ulong>("GuildID");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("tbCurrencies");
                });

            modelBuilder.Entity("MarvBotV3.Database.Tables.TbUsers", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("tbUsers");
                });

            modelBuilder.Entity("MarvBotV3.Database.Tables.tbGoldGambles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("Amount");

                    b.Property<int>("Roll");

                    b.Property<ulong>("UserID");

                    b.Property<string>("Username");

                    b.Property<bool>("Won");

                    b.HasKey("ID");

                    b.ToTable("tbGoldGambles");
                });
#pragma warning restore 612, 618
        }
    }
}
